[package]
name = "manga_updater"
version = "0.6.10"
authors = ["Yvan Sanson <sansonyvan@gmail.com>"]
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
csv = "1.1.6"
futures = "0.3.23"
open = "3.0.2"
reqwest = { version = "0.11.11" }
scraper = "0.13.0"
serial_test = "0.9.0"
structopt = "0.3.26"
text_io = "0.1.12"
tokio = { version = "1.20.1", features = ["full"] }
