[package]
name = "manga_updater"
version = "0.5.6"
authors = ["Yvan Sanson <sansonyvan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.7"
structopt = "0.3"
csv = "1.1"
colour = "0.5.0"
text_io = "0.1.8"
open = "1.4.0"
serial_test = "0.5.1"
