[package]
name = "manga_updater"
version = "0.6.7"
authors = ["Yvan Sanson <sansonyvan@gmail.com>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
reqwest = { version = "0.11.2" }
tokio = { version = "1.4.0", features = ["full"] }
futures = "0.3.13"
structopt = "0.3.21"
csv = "1.1.6"
colour = "0.6.0"
text_io = "0.1.8"
open = "1.6.0"
serial_test = "0.5.1"
