[package]
name = "manga_updater"
version = "0.1.0"
authors = ["Yvan Sanson <yvan.sanson@polytech.univ-montp2.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
reqwest = { version = "0.10", features = ["blocking", "json"] }
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.7"
